name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  phpunit:
    name: "Run tests: PHP ${{ matrix.php }} Symfony ${{ matrix.symfony }} ${{ matrix.dependency }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.4'
        symfony:
          - '4.*'
          - '5.*'
        dependency:
          - 'highest'
          - 'lowest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        with:
          dependency-versions: ${{ matrix.dependency }}

      - name: Clear cache
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ matrix.symfony }}-${{ matrix.dependency }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php }}-${{ matrix.symfony }}-${{ matrix.dependency }}

      - name: Run all tests
        run: composer test
